In [1]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.optimizers import Adam
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from tensorflow.keras.utils import to_categorical

In [2]:
iris = load_iris()
x_data = iris.data
y_data = iris.target

In [3]:
print(y_data)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [4]:
print(x_data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
y_data = to_categorical(y_data, num_classes=3)

In [6]:
print(y_data)

[[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0.

In [7]:
x_train, x_test, y_train, y_test = train_test_split(
x_data, y_data, test_size=0.2, random_state=42
)

In [8]:
model = Sequential()
model.add(Input(shape=(4,)))
model.add(Dense(3, activation='softmax'))

2026-05-06 17:04:02.502977: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M4
2026-05-06 17:04:02.503122: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 16.00 GB
2026-05-06 17:04:02.503128: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 5.92 GB
2026-05-06 17:04:02.503322: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2026-05-06 17:04:02.503342: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


In [9]:
model.compile(
optimizer=Adam(learning_rate=0.05),
loss='categorical_crossentropy',
metrics=['accuracy']
)

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 3)              │            15 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 15 (60.00 B)

 Trainable params: 15 (60.00 B)

 Non-trainable params: 0 (0.00 B)

In [10]:
hist = model.fit(x_train, y_train, epochs=200, verbose=2)

Epoch 1/200


2026-05-06 17:04:19.957647: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:117] Plugin optimizer for device_type GPU is enabled.


4/4 - 2s - 539ms/step - accuracy: 0.3250 - loss: 2.6333
Epoch 2/200
4/4 - 0s - 12ms/step - accuracy: 0.2667 - loss: 1.7756
Epoch 3/200
4/4 - 0s - 12ms/step - accuracy: 0.1000 - loss: 1.5456
Epoch 4/200
4/4 - 0s - 14ms/step - accuracy: 0.3583 - loss: 1.1285
Epoch 5/200
4/4 - 0s - 18ms/step - accuracy: 0.3917 - loss: 0.9663
Epoch 6/200
4/4 - 0s - 11ms/step - accuracy: 0.6333 - loss: 0.8018
Epoch 7/200
4/4 - 0s - 11ms/step - accuracy: 0.7417 - loss: 0.6650
Epoch 8/200
4/4 - 0s - 11ms/step - accuracy: 0.8250 - loss: 0.6000
Epoch 9/200
4/4 - 0s - 11ms/step - accuracy: 0.8417 - loss: 0.5512
Epoch 10/200
4/4 - 0s - 12ms/step - accuracy: 0.8583 - loss: 0.5044
Epoch 11/200
4/4 - 0s - 11ms/step - accuracy: 0.8417 - loss: 0.4833
Epoch 12/200
4/4 - 0s - 11ms/step - accuracy: 0.8500 - loss: 0.4594
Epoch 13/200
4/4 - 0s - 11ms/step - accuracy: 0.9000 - loss: 0.4415
Epoch 14/200
4/4 - 0s - 11ms/step - accuracy: 0.9083 - loss: 0.4263
Epoch 15/200
4/4 - 0s - 11ms/step - accuracy: 0.8667 - loss: 0.4183


In [11]:
loss, acc = model.evaluate(x_test, y_test)
print("Test Accuracy =", acc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 114ms/step - accuracy: 1.0000 - loss: 0.0836
Test Accuracy = 1.0


In [12]:
pred = model.predict(x_test[:5])

print("예측 : ", pred)
print("예측 결과 : ", np.argmax(pred, axis=1))

# 실제값을 클래스 번호로 변환
true_label = np.argmax(y_test[:5], axis=1)
print("실제값 : ", true_label)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step
예측 :  [[1.3773721e-03 9.5778042e-01 4.0842213e-02]
 [9.9468517e-01 5.3148419e-03 8.8215884e-12]
 [1.4817789e-10 4.2843138e-04 9.9957162e-01]
 [1.5100033e-03 9.0042645e-01 9.8063551e-02]
 [6.1773194e-04 9.5591891e-01 4.3463375e-02]]
예측 결과 :  [1 0 2 1 1]
실제값 :  [1 0 2 1 1]
